### ISSUE TITLE
cannnot make mysql2.so on Web App Ruby2.6

### ISSUE THREAD

**Issue by emorima** [Azure-App-Service/ruby#36]
I created Web App based on  Ruby 2.6 for Linux.
And I pushed a simple Rails6 application to local git on Web App and automatically deployed and normally finished.

the application is ...
- Rails6 new application (--skip-yarn --skip-webpack-install --skip-coffee --skip-javascript --database=mysql)
- use MySQL database (on Azure)
- use 1table (just scaffold user table)

I accessed the rails6 app page, the below error occured.
```
2019-09-10T10:01:33.647540873Z /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require': libmariadbclient.so.18: cannot open shared object file: No such file or directory - /tmp/bundle/gems/mysql2-0.5.2/lib/mysql2/mysql2.so (LoadError)
2019-09-10T10:01:33.651693390Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
2019-09-10T10:01:33.651980691Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
2019-09-10T10:01:33.651993691Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
2019-09-10T10:01:33.651998591Z     from /tmp/bundle/gems/mysql2-0.5.2/lib/mysql2.rb:33:in `'
2019-09-10T10:01:33.652712294Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
2019-09-10T10:01:33.653013195Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
2019-09-10T10:01:33.653270496Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
2019-09-10T10:01:33.653282496Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
2019-09-10T10:01:33.653841699Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
2019-09-10T10:01:33.654110300Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
2019-09-10T10:01:33.654122300Z     from /usr/local/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler.rb:114:in `require'
2019-09-10T10:01:33.654126600Z     from /home/site/wwwroot/config/application.rb:7:in `'
2019-09-10T10:01:33.654130900Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
2019-09-10T10:01:33.654486101Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
2019-09-10T10:01:33.654497602Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
2019-09-10T10:01:33.654501702Z     from /tmp/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
2019-09-10T10:01:33.655368405Z     from /tmp/bundle/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:141:in `block in perform'
2019-09-10T10:01:33.655380305Z     from /tmp/bundle/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `tap'
2019-09-10T10:01:33.655384405Z     from /tmp/bundle/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `perform'
2019-09-10T10:01:33.655388005Z     from /tmp/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
2019-09-10T10:01:33.657101412Z     from /tmp/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
2019-09-10T10:01:33.657361613Z     from /tmp/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
2019-09-10T10:01:33.657373513Z     from /tmp/bundle/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
2019-09-10T10:01:33.657672315Z     from /tmp/bundle/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
2019-09-10T10:01:33.657683315Z     from /tmp/bundle/gems/railties-6.0.0/lib/rails/commands.rb:18:in `'
2019-09-10T10:01:33.657687415Z     from bin/rails:9:in `require'
2019-09-10T10:01:33.658013916Z     from bin/rails:9:in `
'
```

I created similar rails app and pushed on Ruby2.4  on August, it run properly.
(mysql2.so was created when `bundle install` )

I found recentrly updated docker image, is there a possibility that it has a relation to this?
https://hub.docker.com/r/appsvc/ruby/tags

**Comment by emorima** [comment]
I contacted the Microsoft Support in Japan  about this issue through my customers.

I've got the reply below:
- There was a lack of dependency on Ruby environment in the latest Kudu.
- set environment variable 'ENABLE_KUDU_LITE = false'

I set the environment variable on my Web App, and the App run correctly.
It seems that this bug is on Kudu, so I close this issue.
